name: "Build/Push github-runner-autoscaler Docker Image"
on: push

jobs:
  extract_version:
    name: "Extract autoscaler version"
    runs-on: ubuntu-latest
    outputs:
      autoscaler_version: ${{ steps.extract_version.outputs.autoscaler_version }}
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4
      - name: "Write version to outputs"
        run: echo autoscaler_version=$(grep -oP '(?<=autoscaler_version\s?=\s?")[^"]*' version.tf) >> "$GITHUB_OUTPUT"
  build_docker_image:
    name: "Build/Push Docker Image"
    needs: extract_version
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Login to ghcr.io"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build/Push Docker Image"
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: runner-autoscaler
          platforms: linux/amd64
          push: true
          sbom: false
          provenance: false
          tags: |
            ghcr.io/privatehive/github-runner-autoscaler:latest
            ghcr.io/privatehive/github-runner-autoscaler:${{ needs.extract_version.outputs.autoscaler_version }}
            ghcr.io/privatehive/github-runner-autoscaler:${{ github.ref_name }}
